version: "3.8"

services:
  
  db: 
   image: mongo:latest
   restart: always
   volumes: 
    - ./init-db:/docker-entrypoint-initdb.d
   ports:
    - 3012:27017
   environment:
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "SCUvvQj8k3"
    MONGO_INITDB_DATABASE: "animalikos"

networks:
  test-animalikos-net:
   driver: bridge